#!/usr/bin/env python3
"""Freeze a small revision-pinned public corpus; raw texts stay outside Git."""
import argparse
import gzip
import hashlib
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlparse
import requests
sys.path.insert(0, str(Path('.cache/python-deps').resolve()))
import fsspec
import pyarrow.parquet as pq
from transformers import AutoTokenizer

SOURCES = {
    'de': ('HuggingFaceFW/fineweb-2', 'data/deu_Latn/train/000_00000.parquet', 10),
    'en': ('HuggingFaceFW/fineweb-edu', 'data/CC-MAIN-2013-20/train-00000-of-00014.parquet', 40),
    'code': ('codeparrot/codeparrot-clean', 'file-000000000001.json.gz', 8),
    'chat': ('HuggingFaceTB/smoltalk', 'data/smol-magpie-ultra/train-00000-of-00006.parquet', 8),
    'math': ('open-web-math/open-web-math', 'data/train-00000-of-00114-5a023365406cb9c4.parquet', 4),
}


def digest(text):
    return hashlib.sha256(text.encode()).hexdigest()


def paragraphs(text):
    return {digest(re.sub(r'\s+', ' ', p).strip().lower())
            for p in text.splitlines() if len(p.strip()) >= 80}


def records(url):
    if url.endswith('.gz'):
        with requests.get(url, stream=True, timeout=90) as response:
            response.raise_for_status()
            with gzip.GzipFile(fileobj=response.raw) as stream:
                for line in stream:
                    yield json.loads(line)
    else:
        with fsspec.open(url, block_size=4 * 1024 * 1024).open() as stream:
            parquet = pq.ParquetFile(stream)
            for batch in parquet.iter_batches(batch_size=128):
                yield from batch.to_pylist()


def main(out):
    out.mkdir(parents=True, exist_ok=False)
    tokenizer = AutoTokenizer.from_pretrained('models/hf-download-test', local_files_only=True)
    excluded = set()
    for folder in ['comparison-2026-09-06', 'plan-heldout-v1', 'head-audit-v1']:
        for path in (Path('benchmarks') / folder).rglob('source.txt'):
            excluded |= paragraphs(path.read_text(encoding='utf-8'))
    all_documents = []
    provenance = {}
    for domain, (repo, filename, count) in SOURCES.items():
        response = requests.get('https://huggingface.co/api/datasets/' + repo, timeout=60)
        response.raise_for_status()
        info = response.json()
        revision = info['sha']
        url = f'https://huggingface.co/datasets/{repo}/resolve/{revision}/{filename}'
        provenance[domain] = dict(repository=repo, revision=revision, file=filename,
                                  card=info.get('cardData', {}))
        used_groups = set()
        selected = 0
        for index, row in enumerate(records(url)):
            if domain == 'chat':
                messages = row.get('messages')
                if not messages:
                    continue
                text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False,
                                                     enable_thinking=False)
            else:
                text = row.get('text', row.get('content', ''))
            if not text or '\ufffd' in text or len(text) > 300000:
                continue
            group = row.get('repo_name') if domain == 'code' else urlparse(row.get('url', '')).hostname
            if domain == 'code' and (row.get('license') not in ['mit', 'apache-2.0', 'bsd-3-clause', 'bsd-2-clause']
                                     or row.get('autogenerated')):
                continue
            if group and group in used_groups:
                continue
            pieces = paragraphs(text)
            if pieces & excluded:
                continue
            tokens = tokenizer.encode(text, add_special_tokens=False)
            if len(tokens) < 1024 or len(set(tokens[:1024])) < 64:
                continue
            # Reserve the first two independent documents per domain before calibration selection.
            split = 'final' if selected < 2 else 'calibration'
            key = f'{domain}-{selected:03d}'
            directory = out / key
            directory.mkdir()
            (directory / 'source.txt').write_text(text, encoding='utf-8')
            chosen = tokens[:640 if split == 'final' else 1024]
            (directory / 'tokens.csv').write_text(','.join(map(str, chosen)))
            (directory / 'record.json').write_text(json.dumps(row, ensure_ascii=False, default=str), encoding="utf-8")
            all_documents.append(dict(id=key, domain=domain, split=split, folder=str(directory.resolve()),
                source_sha256=digest(text), token_sha256=digest(','.join(map(str, chosen))),
                tokens=len(chosen), group=group, row_index=index, source_id=row.get('id'),
                license=row.get('license'), repository=repo, revision=revision, file=filename))
            excluded |= pieces
            if group:
                used_groups.add(group)
            selected += 1
            print(f'{domain}: {selected}/{count+2}', flush=True)
            if selected == count + 2:
                break
        if selected != count + 2:
            raise ValueError(f'Insufficient independent {domain} records')
        (out / 'selection.json').write_text(json.dumps(dict(documents=all_documents, sources=provenance), indent=2))
    calibration = [d for d in all_documents if d['split'] == 'calibration']
    mixture = [d for d in calibration if d['domain'] != 'en'] + [d for d in calibration if d['domain'] == 'en'][:10]
    prose = [d for d in calibration if d['domain'] == 'en']
    for name, documents in [('mixture', mixture), ('prose', prose)]:
        (out / (name + '.json')).write_text(json.dumps(dict(version=1, documents=documents,
            selection='First eligible independent records in pinned first-shard order; not a random corpus sample.',
            tokens=sum(d['tokens'] for d in documents),
            limitation='40 x 1024-token screening subset; Python-only code substitute; longer contexts and 256-sequence expansion deferred.'), indent=2) + '\n')
    final = out / 'final'
    final.mkdir()
    windows = []
    for i, document in enumerate(d for d in all_documents if d['split'] == 'final'):
        directory = Path(document['folder'])
        tokens = list(map(int, (directory / 'tokens.csv').read_text().split(',')))
        (directory / 'prompt.csv').write_text(','.join(map(str, tokens[:512])))
        (directory / 'targets.csv').write_text(','.join(map(str, tokens[512:])))
        windows.append(dict(window=i, folder=str(directory), domain=document['domain'],
                            article_sha256=document['source_sha256'], scored_tokens=128))
    (final / 'quality-windows.json').write_text(json.dumps(dict(version=1, windows=windows,
        calibration_usage='Reserved before fitting; do not use for variant selection.'), indent=2) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, required=True)
    main(parser.parse_args().out)
